# 1.4.4 Smoothing Images

## Kernel Convolution

In [1]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

In [35]:
l=1
kernel = np.array([[0,-1,0], [-1,5,-1], [0,-1,0]], np.float32)

In [36]:
kernel

array([[ 0., -1.,  0.],
       [-1.,  5., -1.],
       [ 0., -1.,  0.]], dtype=float32)

In [37]:
img = np.random.randint(10, size=(12,12))
#img = np.ones((10,10),np.float32)

In [38]:
img

array([[4, 6, 0, 7, 4, 6, 7, 4, 4, 0, 1, 3],
       [1, 3, 3, 5, 3, 3, 8, 0, 0, 1, 1, 8],
       [1, 9, 7, 1, 7, 2, 7, 0, 1, 7, 2, 6],
       [1, 0, 6, 5, 3, 8, 7, 7, 1, 0, 1, 5],
       [1, 9, 3, 3, 9, 5, 1, 7, 9, 9, 3, 2],
       [6, 0, 3, 2, 2, 2, 7, 4, 9, 0, 2, 3],
       [2, 6, 6, 9, 0, 8, 9, 2, 8, 1, 2, 0],
       [3, 3, 5, 2, 3, 0, 6, 8, 1, 7, 8, 5],
       [7, 4, 6, 7, 5, 7, 9, 4, 3, 2, 4, 4],
       [5, 3, 6, 4, 2, 8, 3, 6, 5, 6, 8, 0],
       [1, 6, 0, 6, 5, 1, 9, 2, 4, 8, 4, 4],
       [1, 7, 7, 8, 4, 4, 9, 9, 1, 4, 7, 8]])

In [39]:
h,w=img.shape

In [40]:
print(h,w)

12 12


In [41]:
#[*range(-2,3)]

In [42]:
dst = np.zeros((h,w),np.int)

C:\Users\U301-19\AppData\Local\Temp\ipykernel_1976\2160328971.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dst = np.zeros((h,w),np.int)


In [43]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i,j]=t        

In [44]:
img

array([[4, 6, 0, 7, 4, 6, 7, 4, 4, 0, 1, 3],
       [1, 3, 3, 5, 3, 3, 8, 0, 0, 1, 1, 8],
       [1, 9, 7, 1, 7, 2, 7, 0, 1, 7, 2, 6],
       [1, 0, 6, 5, 3, 8, 7, 7, 1, 0, 1, 5],
       [1, 9, 3, 3, 9, 5, 1, 7, 9, 9, 3, 2],
       [6, 0, 3, 2, 2, 2, 7, 4, 9, 0, 2, 3],
       [2, 6, 6, 9, 0, 8, 9, 2, 8, 1, 2, 0],
       [3, 3, 5, 2, 3, 0, 6, 8, 1, 7, 8, 5],
       [7, 4, 6, 7, 5, 7, 9, 4, 3, 2, 4, 4],
       [5, 3, 6, 4, 2, 8, 3, 6, 5, 6, 8, 0],
       [1, 6, 0, 6, 5, 1, 9, 2, 4, 8, 4, 4],
       [1, 7, 7, 8, 4, 4, 9, 9, 1, 4, 7, 8]])

In [45]:
dst

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,  -4,   0,  11,  -4,  -4,  23, -12,  -6,  -3,  -7,   0],
       [  0,  34,  16, -19,  26, -15,  18, -15,  -3,  31,  -5,   0],
       [  0, -25,  15,  12, -14,  23,  12,  20, -12, -18,  -5,   0],
       [  0,  41,  -6,  -4,  32,   5, -21,  14,  19,  33,   1,   0],
       [  0, -24,   4,  -7,  -3, -12,  19,  -5,  24, -21,   2,   0],
       [  0,  19,   7,  35, -22,  29,  22, -19,  27, -12,  -1,   0],
       [  0,  -3,   8, -14,   8, -24,   4,  27, -21,  23,  22,   0],
       [  0,   1,   8,  18,   6,  13,  25,  -6,   3, -10,  -2,   0],
       [  0,  -6,  17,  -1, -12,  27, -17,  16,   6,   7,  26,   0],
       [  0,  19, -25,  13,  12, -21,  30, -18,   4,  22,  -7,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]])

In [46]:
img = cv2.imread('lena.png', 0)

In [47]:
h,w=img.shape

In [48]:
dst = np.zeros((h-2*l,w-2*l),np.uint8)

In [49]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i-l,j-l]=t 

In [51]:
cv2.imshow('img',img)
cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()